### ISSUE TITLE
unable to import module 'hello/wrap'

### ISSUE THREAD

**Issue by mvanderlee** [cfchou/serverless-python-individually#11]
Followed the example, but I get 
```
{
  "errorMessage": "Unable to import module 'hello/wrap'"
}
```

python2.7

**Comment by lucasventurasc** [comment]
@MichielVanderlee, Hi, do you are facing these problems yet? If yes, can you paste your serverless.yml here and your folder structure?

**Comment by mvanderlee** [comment]
I ran into while comparing this plugin vs https://github.com/ubaniabalogun/serverless-package-python-functions
I ended up using `serverless-package-python-functions` as it fit my needs better. 

Since then I've deleted the test project so can't provide additional info anymore. I'll close the issue.
