### ISSUE TITLE
Problem with new version of pip

### ISSUE THREAD

**Issue by marlontrapp** [cfchou/serverless-python-individually#13]
We started to have problems using the plugin with 'dockerizedPip: True' since yesterday (19/03/2018).

After some search we've found the cause of this error:

https://github.com/cfchou/serverless-python-individually/blob/7c396f596d1c20f23999850aa5b6de47b32525b7/index.js#L319

This check is causing problem when a new version of pip is released and the docker image is not updated with that version. Because pip prints the warning message of new version available in the stderr.  
Is there a reason to check for the size of stderr? The 'ret.error' isn't enough?

**Comment by lucasventurasc** [comment]
I opened a pull request to fix the problem which happens when new pip versions are distributed.

**Comment by Apathyman** [comment]
lucas' solution works for us, we're using a local fork until this can be fixed. I recommend using his branch until chchou approves the pull request.
