### ISSUE TITLE
Issues with running in Travis CI

### ISSUE THREAD

**Issue by carterqw2** [cfchou/serverless-python-individually#3]
Hi @cfchou,

I faced this issue when I was trying to configure Travis CI to deploy my project. Serverless Framework failed with this error
```
  File "gateway/lib/_requirements.py", line 56, in <module>
    sys_stdout.write(b'creating virtualenv {}\n'.format(VENV_DIR))
AttributeError: 'bytes' object has no attribute 'format'
```

This issue is reproducible locally as well.
```
virtualenv -p python3.6 venv
pip install -t lib/ -r requirements.txt
. ./venv/bin/activate
serverless deploy
```

Created PR #2.

**Comment by cfchou** [comment]
Very much appreciate your contribution so that the plugin works for python 3.6!
