### ISSUE TITLE
Does not work in subdirectories

### ISSUE THREAD

**Issue by felschr** [cfchou/serverless-python-individually#5]
When I try to run a deployed Lambda function I get the following error:
`Syntax error in module 'src/stepfunction/cropping/wrap': invalid syntax (wrap.py, line 11)`

The created wrap.py function looks like this:
```py

# vim:fileencoding=utf-8
# wrap.py
# This file is generated on the fly by serverless-python-individually plugin.
import os
import sys

root = os.path.abspath(os.path.join(os.path.dirname(__file__)))
sys.path[0:0] = [root, os.path.join(root, "lib")]

from src/stepfunction/cropping/cropDinA4 import lambda_handler as real_handler # THIS LINE!!!

def handler(event, context):
  return real_handler(event, context)
 ```

I guess this is due to the fact that the function is in a subdirectory.
Is there a way that can be supported?

**Comment by felschr** [comment]
serverless uses forward slashes no matter on which OS:
https://github.com/serverless/serverless/issues/839

I got it working locally and I'll create a pull request for this later today.

**Comment by cfchou** [comment]
Hey @FelschR thanks for the contribution. Sorry for my slow response, I got occupied recently. Anyway, I'll merge your PR later if everything's fine.
